# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.provision :shell, :path => "../../scripts/opal/add-obiba-unstable-apt-repo.sh"
  config.vm.provision :shell, :path => "../../scripts/mica2/install-opal-unstable.sh"
  config.vm.provision :shell, :path => "../../scripts/opal/add-opal-home-fs.sh"
  config.vm.network :forwarded_port, host: 8843, guest: 8443
  config.vm.synced_folder "../../data", "/vagrant_data"

  config.vm.provider :virtualbox do |vb|
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
