#!/bin/sh
### BEGIN INIT INFO
# Provides:          rserve
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start R server at boot time
# Description:       Enable R service.
### END INIT INFO

NAME=Rserve
USER=rserve

case "$1" in
# Start command
start)
  echo "Starting $NAME"
  start-stop-daemon --start --name $NAME --chdir /tmp --chuid $USER --exec /usr/bin/R -- CMD Rserve --vanilla > /var/lib/rserve/Rserve.log 2>&1 &
  ;;
# Stop command
stop)
  echo "Stopping $NAME"
  killall Rserve && echo "$NAME stopped successfully"
  ;;
# Restart command
restart)
  $0 stop
  sleep 5
  $0 start
  ;;
force-reload)
  $0 stop
  sleep 5
  $0 start
  ;;
*)
  echo "Usage: /etc/init.d/$NAME {start|restart|stop}"
  exit 1
  ;;
esac

exit 0
